CREATE TABLE STATUS_EVENT
(
    EVENT_ID      RAW(16)                             NOT NULL,
    EVENT_PAYLOAD BLOB                                NOT NULL,
    EVENT_STATUS  VARCHAR2(50)                        NOT NULL,
    EVENT_TYPE    VARCHAR2(100)                       NOT NULL,
    SAGA_ID       RAW(16),
    EVENT_OUTCOME VARCHAR2(100)                       NOT NULL,
    REPLY_CHANNEL VARCHAR2(100),
    CREATE_USER   VARCHAR(32)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(32)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STATUS_EVENT_PK PRIMARY KEY (EVENT_ID)
);
CREATE INDEX STATUS_EVENT_EVENT_STATUS_IDX ON STATUS_EVENT (EVENT_STATUS) TABLESPACE API_GRAD_STATUS_IDX;
CREATE INDEX STATUS_EVENT_SAGA_ID_IDX ON STATUS_EVENT (SAGA_ID) TABLESPACE API_GRAD_STATUS_IDX;
CREATE INDEX STATUS_EVENT_EVENT_TYPE_IDX ON STATUS_EVENT (EVENT_TYPE) TABLESPACE API_GRAD_STATUS_IDX;


CREATE TABLE STATUS_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT STATUS_SHEDLOCK_PK PRIMARY KEY (NAME)
);
COMMENT ON TABLE STATUS_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

