---
apiVersion: v1
kind: Template
labels:
  template: 'educ-grad-graduation-status-api-template'
metadata:
  name: 'educ-grad-graduation-status-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: educ-grad-graduation-status-api-pipeline
      name: educ-grad-graduation-status-api-pipeline
      namespace: 77c02f-tools
    spec:
      source:
        git:
          ref: main
          uri: 'https://github.com/bcgov/EDUC-GRAD-GRADUATION-STATUS-API'
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: tools/jenkins/Jenkinsfile-api
